#!/usr/bin/env python3
"""Generate the constant tables the firmware needs (dsp_tables.h).

Two tables are emitted, both in Q15 signed 16-bit format and both destined for
PROGMEM so they cost zero SRAM:

  * HAMMING_Q15[64] - analysis window, w[n] = 0.54 - 0.46*cos(2*pi*n/(N-1))
  * SINE_Q15[64]    - one full period of sin(2*pi*n/64), used by the radix-2
                      FFT for both sine and cosine twiddles (cos is read at
                      index n+16, i.e. a quarter period ahead).

Run:  python3 tools/gen_tables.py > include/dsp_tables.h
"""

import math
import sys

N = 64


def q15(x: float) -> int:
    """Round a float in [-1, 1] to Q15 and clamp to int16 range."""
    v = int(round(x * 32767.0))
    return max(-32768, min(32767, v))


def emit(name: str, values, comment: str) -> None:
    print(f"/* {comment} */")
    print(f"static const int16_t {name}[{len(values)}] PROGMEM = {{")
    for i in range(0, len(values), 8):
        row = ", ".join(f"{v:6d}" for v in values[i:i + 8])
        print(f"    {row},")
    print("};")
    print()


def main() -> None:
    hamming = [q15(0.54 - 0.46 * math.cos(2.0 * math.pi * n / (N - 1))) for n in range(N)]
    sine = [q15(math.sin(2.0 * math.pi * n / N)) for n in range(N)]

    print("/* AUTOGENERATED by tools/gen_tables.py - do not edit by hand. */")
    print("#ifndef DSP_TABLES_H")
    print("#define DSP_TABLES_H")
    print()
    print('#include <stdint.h>')
    print('#include "pgm_compat.h"')
    print()
    emit("HAMMING_Q15", hamming,
         "Hamming window, 64 points, Q15: w[n] = 0.54 - 0.46*cos(2*pi*n/63)")
    emit("SINE_Q15", sine,
         "sin(2*pi*n/64) in Q15; cosine twiddle = SINE_Q15[(n + 16) & 63]")
    print("#endif /* DSP_TABLES_H */")


if __name__ == "__main__":
    sys.exit(main())
