#!/usr/bin/env python3
"""Convert a WAV file into `success_audio.h` for the voice parking lock.

The firmware streams the result straight out of flash at 8 kHz through the
6-bit R-2R ladder on PD2..PD7, one byte per sample, so the header is just a
PROGMEM array of 0..63 codes plus its length.

Typical use (instructor, after recording or synthesising the Persian phrase
"ورود مجاز است"):

    python3 tools/wav_to_6bit_header.py assets/success_fa.wav \
        -o include/success_audio.h

Flash cost is exactly one byte per sample: 8000 bytes per second of audio. The
--max-seconds guard (default 1.8 s = 14400 bytes) exists because the ATmega328P
only has 32 KB of flash and the rest of the firmware needs about 10 KB of it.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wavkit  # noqa: E402


def render_header(codes: list[int], name: str, rate: int, source: str,
                  placeholder: bool) -> str:
    """Build the C header text for a list of 6-bit codes."""
    guard = f"{name}_H"
    lines = [
        "/* AUTOGENERATED by tools/wav_to_6bit_header.py - do not edit by hand.",
        " *",
        f" * source        : {source}",
        f" * sample rate   : {rate} Hz",
        " * format        : unsigned 6-bit PCM, one sample per byte, codes 0..63",
        f" * samples       : {len(codes)}",
        f" * duration      : {len(codes) / rate:.3f} s",
        f" * flash cost    : {len(codes)} bytes",
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        '#include "pgm_compat.h"',
        "",
    ]
    if placeholder:
        lines += [
            "/* ---------------------------------------------------------------------",
            " * THIS IS A PLACEHOLDER TEST TONE, NOT THE PERSIAN SUCCESS MESSAGE.",
            " *",
            " * No Persian text-to-speech engine was available when this repository was",
            " * generated, and inventing an audio clip and labelling it as the phrase",
            " * \"ورود مجاز است\" would be a lie about what the firmware plays. So this",
            " * file instead contains a DAC validation signal: a 0..63 staircase ramp",
            " * followed by a 1 kHz sine. Both are easy to recognise on an oscilloscope",
            " * and prove the R-2R ladder, the PORTD masking and the Timer2 playback",
            " * ISR all work.",
            " *",
            " * To ship the real message, record or synthesise `success_fa.wav` and run:",
            " *   python3 tools/wav_to_6bit_header.py assets/success_fa.wav \\",
            " *       -o include/success_audio.h",
            " * ------------------------------------------------------------------- */",
            f"#define {name}_IS_PLACEHOLDER 1",
            "",
        ]
    else:
        lines += [f"#define {name}_IS_PLACEHOLDER 0", ""]

    lines += [
        f"#define {name}_RATE_HZ {rate}u",
        f"#define {name}_LEN {len(codes)}u",
        "",
        f"static const uint8_t {name}_PCM6[{len(codes)}] PROGMEM = {{",
    ]
    for i in range(0, len(codes), 16):
        lines.append("    " + ", ".join(f"{c:2d}" for c in codes[i:i + 16]) + ",")
    lines += ["};", "", f"#endif /* {guard} */", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("wav", help="input WAV file (any rate, mono or stereo, PCM)")
    p.add_argument("-o", "--output", default="success_audio.h", help="header file to write")
    p.add_argument("--name", default="SUCCESS_AUDIO", help="C identifier prefix")
    p.add_argument("--rate", type=int, default=wavkit.FIRMWARE_RATE_HZ,
                   help="target sample rate (must match the firmware's Timer2 rate)")
    p.add_argument("--max-seconds", type=float, default=1.8,
                   help="refuse to generate more audio than this (flash guard)")
    p.add_argument("--no-normalize", action="store_true",
                   help="skip peak normalisation (keep the source level)")
    p.add_argument("--peak", type=float, default=0.95,
                   help="normalisation target peak, 0..1")
    p.add_argument("--placeholder", action="store_true",
                   help="mark the header as a placeholder test signal, not the real message")
    args = p.parse_args(argv)

    samples, src_rate = wavkit.read_wav(args.wav)
    if not samples:
        print(f"error: {args.wav} contains no audio", file=sys.stderr)
        return 2

    if src_rate > args.rate:
        # Guard the decimation: anything above Nyquist would fold back into the
        # speech band we care about.
        samples = wavkit.lowpass(samples, src_rate, args.rate * 0.45)
    samples = wavkit.resample(samples, src_rate, args.rate)
    samples = wavkit.remove_dc(samples)
    if not args.no_normalize:
        samples = wavkit.normalize(samples, args.peak)

    limit = int(args.max_seconds * args.rate)
    if len(samples) > limit:
        print(f"error: {len(samples)} samples ({len(samples)/args.rate:.2f} s) exceeds "
              f"--max-seconds {args.max_seconds} ({limit} bytes of flash). "
              f"Trim the recording or raise the limit deliberately.", file=sys.stderr)
        return 2

    codes = wavkit.quantize_6bit(samples)
    text = render_header(codes, args.name, args.rate, os.path.basename(args.wav),
                         args.placeholder)
    with open(args.output, "w") as f:
        f.write(text)
    print(f"{args.output}: {len(codes)} samples, {len(codes)/args.rate:.3f} s, "
          f"{len(codes)} bytes of flash")
    return 0


if __name__ == "__main__":
    sys.exit(main())
